version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /wdl/MAS-seq_data-processing_main.wdl
    testParameterFiles:
      - /optional.json
    name: masseq_main
  - subclass: WDL
    primaryDescriptorPath: /wdl/skera_w_QCplots.wdl
    testParameterFiles:
      - /optional.json
    name: pbskera_main
  - subclass: WDL
    primaryDescriptorPath: /wdl/masseq_bulk_demux.wdl
    testParameterFiles:
      - /optional.json
    name: bulk_demux
  - subclass: WDL
    primaryDescriptorPath: /wdl/pb_refine_sc_plus_bulk.wdl
    testParameterFiles:
      - /optional.json
    name: pbrefine_main
  - subclass: WDL
    primaryDescriptorPath: /wdl/merge_refine_bams.wdl
    testParameterFiles:
      - /optional.json
    name: merge_main
  - subclass: WDL
    primaryDescriptorPath: /wdl/pb_sc_lima_plus_isoseq.wdl
    testParameterFiles:
      - /optional.json
    name: sc_kinnex_lima_plus_isoseq   
  - subclass: WDL
    primaryDescriptorPath: /wdl/pb_sc_groupdedup.wdl
    testParameterFiles:
      - /optional.json
    name: sc_isoseq_groupdedup     
  - subclass: WDL
    primaryDescriptorPath: /wdl/tasks/pbtools.wdl
    testParameterFiles:
      - /optional.json
    name: pbtools_tasklib

