version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /wdl/masseq_bulk_demux.wdl
    testParameterFiles:
      - /optional.json
    name: bulk_demux
  - subclass: WDL
    primaryDescriptorPath: /wdl/tasks/pbtools.wdl
    testParameterFiles:
      - /optional.json
    name: pbtools