version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /wdl/MAS-seq_data-processing_main.wdl
    testParameterFiles:
      - /optional.json
  - subclass: WDL
    primaryDescriptorPath: /wdl/tasks/pbtools.wdl
    testParameterFiles:
      - /optional.json